# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\"\x1c\n\rDeleteRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\"\x1f\n\x0e\x44\x65leteResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"#\n\x14RegistrationResponse\x12\x0b\n\x03uid\x18\x01 \x01(\x05\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"E\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"G\n\x13RegistrationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\";\n\x15\x41uthenticationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x16\n\x05Token\x12\r\n\x05value\x18\x01 \x01(\t\"[\n\rUpdateRequest\x12\x13\n\x0bnewUsername\x18\x01 \x01(\t\x12\x13\n\x0bnewPassword\x18\x02 \x01(\t\x12\x13\n\x0boldPassword\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x04 \x01(\x05\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xaa\x02\n\x15\x41uthenticationService\x12=\n\x0cRegisterUser\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\"\x00\x12-\n\x0b\x43reateToken\x12\x16.AuthenticationRequest\x1a\x06.Token\x12!\n\x0bVerifyToken\x12\x06.Token\x1a\n.BoolValue\x12\"\n\x0c\x44\x65stroyToken\x12\x06.Token\x1a\n.BoolValue\x12-\n\nUpdateUser\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12-\n\nDeleteUser\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseB\x10\n\x0e\x63om.grpc.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.grpc.proto'
  _globals['_DELETEREQUEST']._serialized_start=24
  _globals['_DELETEREQUEST']._serialized_end=52
  _globals['_DELETERESPONSE']._serialized_start=54
  _globals['_DELETERESPONSE']._serialized_end=85
  _globals['_REGISTRATIONRESPONSE']._serialized_start=87
  _globals['_REGISTRATIONRESPONSE']._serialized_end=122
  _globals['_BOOLVALUE']._serialized_start=124
  _globals['_BOOLVALUE']._serialized_end=150
  _globals['_USER']._serialized_start=152
  _globals['_USER']._serialized_end=221
  _globals['_REGISTRATIONREQUEST']._serialized_start=223
  _globals['_REGISTRATIONREQUEST']._serialized_end=294
  _globals['_AUTHENTICATIONREQUEST']._serialized_start=296
  _globals['_AUTHENTICATIONREQUEST']._serialized_end=355
  _globals['_TOKEN']._serialized_start=357
  _globals['_TOKEN']._serialized_end=379
  _globals['_UPDATEREQUEST']._serialized_start=381
  _globals['_UPDATEREQUEST']._serialized_end=472
  _globals['_UPDATERESPONSE']._serialized_start=474
  _globals['_UPDATERESPONSE']._serialized_end=507
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=510
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=808
# @@protoc_insertion_point(module_scope)
